config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: {minimum: 3, maximum: 50}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    
    def index
        @articles = Article.all
    end
    
    def new
        @article = Article.new
    end
    
    def edit
        
    end
    
    def create
        @article = Article.new(article_params)
        if @article.save
            #do something
            flash[:notice] = "Article was successfully created!"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end
    
    def update
        
        if @article.update(article_params
        )
            flash[:notice] = "Article was successfully updated"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end
    
    def show
        
    end
    
    def destroy
       @article.destroy
       flash[:danger] = "Article was successfully deleted!"
       redirect_to articles_path
    end
    
    private
    def set_article
        @article = Article.find(params[:id])
    end
    
    def article_params
        params.require(:article).permit(:title, :description) 
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   def home
       
   end
   
   def about
       
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <div class="error-messages">
        <h2>The following errors prevented the article from being created...</h2>
        <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= form_for @article do |f| %>
    <p>
        <%= f.label :title %> <br />
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %> <br />
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

<%= link_to "Back to articles listing", articles_path %>

app/views/articles/edit.html.erb
<h1>Edit existing artice</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<style>
    .padding {margin: 0 0 15px;}
</style>

<h1 align="center">Listing all articles</h1>
<%= link_to "Create New Article", new_article_path, class: "btn btn-xs btn-primary padding" %>
<% @articles.each do |article| %>

    <div class="row">
    
        <div class="">
        
            <div class="well well-lg">
        
                <div class="article-title">
        
                    <%= link_to article.title, article_path(article) %>
        
                </div>
        
                <div class="article-body">
        
                    <%= truncate(article.description, length: 100) %>
        
                </div>
        
                <div class="article-actions">
        
                    <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
        
                    <%= link_to "Delete this article", article_path(article), method: :delete,
        
                    data: { confirm: "Are you sure you want to delete the article?"},
        
                            class: "btn btn-xs btn-danger" %>
        
                </div>
        
            </div>
        
        </div>
    
    </div>

<% end %>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>

<div class="">

    <h4 class="center"><strong>Description:</strong></h4>
    
    <br>
    
    <%= simple_format(@article.description) %>
    
    <div class="article-actions">
    
        <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
        
        <%= link_to "Delete this article", article_path(@article), method: :delete,
        
        data: { confirm: "Are you sure you want to delete the article?"},
        
        class: "btn btn-xs btn-danger" %>
        
        <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
    
    </div>

</div>

app/views/layouts/_banner.html.erb
<%= image_tag 'https://image.ibb.co/hDpX7k/alpha_blog_banner.jpg', :class => "banner" %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="nav">
  <div class="nav-content my-container">
    <div class="logo"></div>
    <ul>
      <li><%= link_to "Home", root_path, class: "nav-links" %></li>
      <li><%= link_to "About", about_path, class:"nav-links" %></li>
      <li><%= link_to "Artilces", articles_path, class: "nav-links" %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/banner' %>
  <%= render 'layouts/messages' %>
  <div class="my-container">
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

app/views/pages/home.html.erb
<style>
    body {
        margin: 0;
        padding: 0;
        width: 100%;
    }
    .banner {
        display: block;
        width: 100%;
    }
    .nav {background-color: rgba(0,0,0,.5);}
    .nav-links {color: #fff;}
    .nav-links:hover {color: #fff;}
</style>